In [1]:

#Comment out any of the below installations if already installed.
# pip install tensorflow
# pip install keras
# pip install opencv-python 

In [2]:
#Import dependencies
#Load and inspect images using the Python Imaging Library (PIL)
from PIL import Image
import os
import numpy as np
import cv2
import pickle


In [3]:
# Create a list of y_labels and their file paths
# The names are based on the name of the directory where the images were stored (i.e., benign, guns, knives, etc... )

ylist = []
# Specify the directory containing the images
image_dir = "../Data/X_Ray Image DataSet"
# Iterate over the files in the directory
for root, dirs, files in os.walk(image_dir):
    for file in files:
        # Check if the file is a PNG image
        if file.endswith(".png"):
            # Construct the full file path
            file_path = os.path.join(root, file)
            
            # append name of directory to list
            ylist.append(root.split("\\")[-1])
            
            # Load the image
            image = Image.open(file_path)
            
            # Convert the image to grayscale if needed
            if image.mode != "L":
                image = image.convert("L")
                
            # # Display image information to understand what else needs to be done with it. For example, image sizes vary.
            # print("Image Path:", file_path)
            print("Image Size:", image.size)
            # print("Image Mode:", image.mode)
            # print("Image Format:", image.format)
            # print()

# convert list to np array
y=np.array(ylist)

Image Size: (850, 850)
Image Size: (1688, 1692)
Image Size: (407, 407)
Image Size: (407, 407)
Image Size: (2136, 1712)
Image Size: (2136, 1712)
Image Size: (290, 530)
Image Size: (322, 511)
Image Size: (2136, 1712)
Image Size: (2136, 1712)
Image Size: (314, 516)
Image Size: (303, 513)
Image Size: (2136, 1712)
Image Size: (2136, 1712)
Image Size: (407, 407)
Image Size: (407, 407)
Image Size: (407, 407)
Image Size: (1688, 1692)
Image Size: (850, 850)
Image Size: (850, 850)
Image Size: (1688, 1692)
Image Size: (332, 391)
Image Size: (1688, 1692)
Image Size: (407, 407)
Image Size: (407, 407)
Image Size: (2136, 1712)
Image Size: (281, 511)
Image Size: (2136, 1712)
Image Size: (327, 483)
Image Size: (347, 524)
Image Size: (339, 518)
Image Size: (2136, 1712)
Image Size: (272, 536)
Image Size: (407, 407)
Image Size: (407, 407)
Image Size: (287, 536)
Image Size: (1688, 1692)
Image Size: (850, 850)
Image Size: (850, 850)
Image Size: (850, 850)
Image Size: (1688, 1692)
Image Size: (2688, 2208)
Im

Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (601, 1241)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (601, 1241)
Image Size: (601, 1241)
Image Size: (601, 1241)
Image Size: (1258, 1258)
Image Size: (601, 1241)
Image Size: (601, 1241)
Image Size: (1258, 1258)
Image Size: (601, 1241)
Image Size: (601, 1241)
Image Size: (1258, 1258)
Image Size: (601, 1241)
Image Size: (601, 1241)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (601, 1241)
Image Size: (601, 1241)
Image Size: (601, 1241)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (

Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (867, 939)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (587, 1011)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (791, 1044)
Image Size: (861, 861)


In [4]:
# Convert X variables/independent variables/Images to NumPy Arrays. Store these arrays into image_arrays.  
# The NumPy library provides support for working with
# numerical data in Python.
# Create an empty list to store the X/image arrays
image_arrays = []

# Iterate over the files in the directory
for root, dirs, files in os.walk(image_dir):
    for file in files:
        # Check if the file is a PNG image
        if file.endswith(".png"):
            # Construct the full file path
            file_path = os.path.join(root, file)
            
            # Load the image
            image = Image.open(file_path)
            
            # Convert the image to a NumPy array
            image_array = np.array(image)
            
            # Append the image array to the list
            image_arrays.append(image_array)
            
# Print the image arrays
for image_array in image_arrays:
    print(image_array)

[[238 237 238 ... 236 237 237]
 [237 237 238 ... 237 237 237]
 [237 238 236 ... 236 237 237]
 ...
 [237 237 238 ... 237 238 237]
 [237 238 237 ... 238 239 237]
 [237 237 238 ... 237 238 236]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[226 226 226 ... 226 226 226]
 [226 226 226 ... 226 226 226]
 [226 226 226 ... 226 226 226]
 ...
 [226 226 226 ... 224 224 224]
 [226 226 226 ... 224 224 224]
 [226 226 226 ... 224 224 224]]
[[223 224 225 ... 225 225 225]
 [223 224 225 ... 225 225 225]
 [223 224 225 ... 225 225 225]
 ...
 [224 224 224 ... 225 225 224]
 [223 223 223 ... 225 224 223]
 [223 223 223 ... 225 224 223]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]
 [255 255

In [5]:
# print # of images being stored (Excludes "Dangerous" category of images)
print(f" Converted {len(image_arrays)} images into numpy arrays")

 Converted 3214 images into numpy arrays


In [6]:
# Preprocess Images for Machine Learning.  
# Resize the images to a consistent size 
# Specify the target size
target_size = (224, 224)

# Initialize an empty list to store resized image arrays
resized_image_arrays = []

# Iterate over the image arrays
for image_array in image_arrays:
    # Convert the image array back to PIL image
    image = Image.fromarray(image_array)
    
    # Resize the image
    #resized_image = image.resize(target_size)
    resized_image = image.resize(target_size, resample = Image.LANCZOS)
    # Convert the resized image back to NumPy array
    resized_image_array = np.array(resized_image)#.astype(np.float32)
    # append image to resized_image_arrays
    resized_image_arrays.append(resized_image_array)
    
# Print the resized image array
print(resized_image_arrays)

[array([[237, 237, 237, ..., 236, 237, 237],
       [237, 237, 238, ..., 237, 237, 237],
       [237, 237, 238, ..., 237, 236, 236],
       ...,
       [237, 238, 237, ..., 237, 237, 237],
       [238, 237, 237, ..., 237, 237, 237],
       [237, 238, 237, ..., 237, 237, 237]], dtype=uint8), array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8), array([[226, 226, 226, ..., 226, 226, 226],
       [226, 226, 226, ..., 226, 226, 226],
       [226, 226, 226, ..., 226, 226, 226],
       ...,
       [226, 226, 226, ..., 225, 224, 224],
       [226, 226, 226, ..., 225, 224, 224],
       [226, 226, 226, ..., 225, 224, 224]], dtype=uint8), array([[223, 225, 223, ..., 225, 225, 225],
       [223, 225, 223, ..., 225, 225, 225],
       [223, 225, 223, ..., 224, 224, 

In [7]:
# Remove unwanted noise in the images to smooth them out (i.e., less grainy).
# When looking at denoising techniques, we settled on the OpenCV library.
# Normalize data  
# Create an empty list to store the denoised and normalized image arrays
denoised_image_arrays = []
#counter
i = 0

# Iterate over the image arrays
for image_array in resized_image_arrays:
    # print sets of 50 images
    if i%50==0:
        print(f"reading image number {i}")
    # Apply denoising filter and normalizing
    denoised_image_array = cv2.fastNlMeansDenoising(image_array, None, h=10, templateWindowSize=7, 
                                                searchWindowSize=21).astype(np.float32)/255
    
    denoised_image_array = denoised_image_array.reshape(image_array.shape)
    # print denoised_image_arraye
    #display(denoised_image_array)
    # Append the denoised image array to the list
    denoised_image_arrays.append(denoised_image_array)

    # add 1 to counter
    i=i+1
# Print the denoised image arrays
for i, denoised_image_array in enumerate(denoised_image_arrays):
    print(f"Values of denoised image {i}:", denoised_image_array)

reading image number 0
reading image number 50
reading image number 100
reading image number 150
reading image number 200
reading image number 250
reading image number 300
reading image number 350
reading image number 400
reading image number 450
reading image number 500
reading image number 550
reading image number 600
reading image number 650
reading image number 700
reading image number 750
reading image number 800
reading image number 850
reading image number 900
reading image number 950
reading image number 1000
reading image number 1050
reading image number 1100
reading image number 1150
reading image number 1200
reading image number 1250
reading image number 1300
reading image number 1350
reading image number 1400
reading image number 1450
reading image number 1500
reading image number 1550
reading image number 1600
reading image number 1650
reading image number 1700
reading image number 1750
reading image number 1800
reading image number 1850
reading image number 1900
reading i

Values of denoised image 2262: [[0.5882353  0.5882353  0.5882353  ... 0.7764706  0.7764706  0.7764706 ]
 [0.5882353  0.5882353  0.5882353  ... 0.7764706  0.7764706  0.7764706 ]
 [0.5882353  0.5882353  0.5882353  ... 0.7764706  0.7764706  0.7764706 ]
 ...
 [0.48235294 0.48235294 0.48235294 ... 0.50980395 0.50980395 0.50980395]
 [0.48235294 0.48235294 0.48235294 ... 0.50980395 0.50980395 0.50980395]
 [0.48235294 0.48235294 0.48235294 ... 0.50980395 0.50980395 0.50980395]]
Values of denoised image 2263: [[0.50980395 0.50980395 0.50980395 ... 0.36078432 0.36078432 0.3647059 ]
 [0.50980395 0.50980395 0.50980395 ... 0.36078432 0.36078432 0.3647059 ]
 [0.50980395 0.50980395 0.50980395 ... 0.36078432 0.36078432 0.3647059 ]
 ...
 [0.5176471  0.5176471  0.5176471  ... 0.43137255 0.43137255 0.43137255]
 [0.5176471  0.5176471  0.5176471  ... 0.43137255 0.43137255 0.43137255]
 [0.5176471  0.5176471  0.5176471  ... 0.43137255 0.43137255 0.43137255]]
Values of denoised image 2264: [[0.4627451  0.4627

In [8]:
# create path for pickle file
path = '../Data/x-ray.pkl'

# Open a new file named 'img.pkl' with write permission
with open(path, 'wb') as file:
    # Use pickle.dump to store the list of images
    pickle.dump(denoised_image_arrays, file)

In [9]:
#print y values
y

array(['../Data/X_Ray Image DataSet/Razor Blades',
       '../Data/X_Ray Image DataSet/Razor Blades',
       '../Data/X_Ray Image DataSet/Razor Blades', ...,
       '../Data/X_Ray Image DataSet/Throwing Star',
       '../Data/X_Ray Image DataSet/Throwing Star',
       '../Data/X_Ray Image DataSet/Throwing Star'], dtype='<U41')

In [10]:
# Save y to a CSV file
np.savetxt('../Data/Y_Labels/y_labels.csv', y, fmt='%s', delimiter=',')

In [11]:
#checking for imbalnce data
unique_values, counts = np.unique(y, return_counts=True)

# Print unique values and their counts
for value, count in zip(unique_values, counts):
    print(f"{value}: {count}")

../Data/X_Ray Image DataSet/Benign: 737
../Data/X_Ray Image DataSet/Guns: 624
../Data/X_Ray Image DataSet/Knives: 776
../Data/X_Ray Image DataSet/Razor Blades: 403
../Data/X_Ray Image DataSet/Throwing Star: 674
